version: '3.8'
services:
  # Kotlin backend service
  backend:
    image: gradle:8.8-jdk17
    tty: true
    stdin_open: true
    working_dir: /app
    environment:
      - APP_ENV=dev
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
      - gradle-cache:/root/.gradle
    command: >
      bash -c "cd /app &&
      apt-get update && apt-get install -y dos2unix &&
      dos2unix gradlew &&
      chmod +x gradlew &&
      ./gradlew runDevApi ||
      (>&2 echo 'Backend failed to start... keeping container alive for debugging' && sleep infinity)"
    networks:
      - app-network

  # React frontend service
  frontend:
    image: node:18-alpine
    tty: true
    stdin_open: true
    working_dir: /app
    environment:
      - VITE_APP_ENV=development
      - VITE_API_BASE_URL=http://backend:8080/api
    ports:
      - "5173:5173"
    volumes:
      - ./frontend-react:/app
    command: >
      sh -c "cd /app &&
      npm install &&
      npm run dev -- --port 5173 --host 0.0.0.0 --no-open ||
      (>&2 echo 'Frontend failed to start... keeping container alive for debugging' && sleep infinity)"
    networks:
      - app-network
    depends_on:
      - backend

volumes:
  gradle-cache:

networks:
  app-network:
    driver: bridge