---
galaxy_info:
  role_name: app
  author: Your Name
  description: Role for deploying JSONPlaceholder Downloader application
  license: MIT
  min_ansible_version: '2.12'
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - java
    - webservice
    - jsonplaceholder

dependencies: []