---
galaxy_info:
  role_name: frontend
  author: Your Name
  description: Role for deploying React frontend for JSONPlaceholder Downloader
  license: MIT
  min_ansible_version: '2.12'
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - web
    - frontend
    - react
    - vite

dependencies: []