---
- name: Deploy JSONPlaceholder Downloader Application
  hosts: app_servers
  become: true
  
  pre_tasks:
    - name: Verify environment
      ansible.builtin.debug:
        msg: "Deploying {{ app_name | default('jsonplaceholder-downloader') }} version {{ app_version | default('1.0-SNAPSHOT') }} to {{ inventory_hostname }}"
      tags: [always]
    
    - name: Check connectivity
      ansible.builtin.ping:
      tags: [pre-check]
    
    - name: Check internet connectivity
      ansible.builtin.command: ping -c 4 8.8.8.8
      register: ping_result
      changed_when: false
      failed_when: false
      tags: [pre-check]
      
    - name: Show internet connectivity status
      ansible.builtin.debug:
        msg: "Internet connectivity: {{ 'OK' if ping_result.rc == 0 else 'FAILED' }}"
      tags: [pre-check]
      
    - name: Check package repository connectivity
      ansible.builtin.command: ping -c 2 archive.ubuntu.com
      register: repo_ping
      changed_when: false
      failed_when: false
      tags: [pre-check]
      
    - name: Show repository connectivity status
      ansible.builtin.debug:
        msg: "Package repository connectivity: {{ 'OK' if repo_ping.rc == 0 else 'FAILED' }}"
      tags: [pre-check]
    
    - name: Check required disk space
      ansible.builtin.command: df -h {{ app_dir | default('/opt/jsonplaceholder') }}
      register: disk_space
      changed_when: false
      failed_when: false
      tags: [pre-check]
      
    - name: Display disk space
      ansible.builtin.debug:
        var: disk_space.stdout_lines
      when: disk_space.stdout is defined
      tags: [pre-check]

  roles:
    - role: app
      tags: [app, backend]
    - role: frontend
      tags: [frontend]

  post_tasks:
    - name: Deployment summary
      ansible.builtin.debug:
        msg: |
          Deployment successful!
          Backend API: http://srv14.mikr.us:{{ app_external_port | default(40060) }}/api/info
          Frontend: http://srv14.mikr.us:{{ frontend_external_port | default(40061) }}/
      tags: [always]
    
    - name: Record deployment completion time
      ansible.builtin.set_fact:
        deployment_completed: "{{ ansible_date_time.iso8601 }}"
      tags: [report]
      
    - name: Deployment duration
      ansible.builtin.debug:
        msg: "Deployment completed at {{ deployment_completed }}"
      tags: [report]